### ISSUE TITLE
el-get cannot install flycheck on windows

### ISSUE THREAD

**Issue by johnfredcee** [dimitri/el-get#2034]
Installation/update of flycheck on Windows fails with the following backtrace (MSys2/mingw64)

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  w32-short-file-name(nil)
  el-get-shell-quote-program("makeinfo")
...

Inspection of el-get-shell-quote-program reveals it is passing the result of (find-executable "makeinfo") to w32-short-file-name, and failing because makeinfo is not an .exe but a script with no file suffix.

**Comment by priyadarshan** [comment]
> Putting a makeinfo.bat in exec-path should work fine.

I am sorry to resurrect this, but would you have advice on how to have makeinfo.bat?

5 years later (January 2020) I have exactly the same problem: Native Windows Emacs 27.0.50, texinfo installed via msys2 and also ezwinports, both available on path.

**Comment by npostavs** [comment]
> Native Windows Emacs 27.0.50, texinfo installed via msys2 and also ezwinports, both available on path.

The ezwinports version should provide a normal `makeinfo.exe`, which w32 Emacs should be able run without a wrapping bat file. Make sure it's listed first in `exec-path`.

**Comment by priyadarshan** [comment]
I have put ezwinports' `makeinfo.exe` first on `exec-path` so that I can see it starting and returning proper message by doing `M-!` `maketext.exe` with no arguments,

```
makeinfo: missing file argument.
Try `makeinfo --help' for more information.
```

But then built process still stops. For example, when installing `transient` (needed by magit and others), I get:

```
 mingw32-make[1]: Entering directory 'c:/home/.config/emacs/el-get/transient/docs'
process_begin: CreateProcess(NULL, printf "Generating transient.info\n", ...) failed.
make (e=2): The system cannot find the file specified.

mingw32-make[1]: *** [Makefile:30: transient.info] Error 2
mingw32-make[1]: Leaving directory 'c:/home/.config/emacs/el-get/transient/docs'
mingw32-make: *** [Makefile:32: info] Error 2
```

It is not an `el-get` issue, I am sorry to bother you here.

Still, I am blocked from using my favourite Emacs package manager by an unclear situation. I could manually edit needed recipes, but I was using `el-get` on FreeBSD and OSX for the completeness of the install. It would be a pity not to carry that over to Windows.

**Comment by npostavs** [comment]
Ah, looks like you don't have `printf` (a Unix command line utility). I think we should avoid calling `make` on `windows/nt` for transient, just as we currently avoid this for magit. See #2754.

**Comment by priyadarshan** [comment]
I see now, it was quite obscure to understand. I will wait for the PR to be merged and test again.

Would it be fine in the future to open tickets for similar cases (where Unix commands are missing on `windows/nt` systems?
