### ISSUE TITLE
duplicated init file in the el-get-bundle initial directory

### ISSUE THREAD

**Issue by enzochiau** [dimitri/el-get#2172]
I am using `el-get-bundle` to install packages. I found some package's init are duplicated in the `el-get-bundle-init-directory`.

For example it will have files like `_xxxx-15-_iedit.el` and `_xxxx-16-_iedit.el` with the same content.

**Comment by tarao** [comment]
This happens when you have multiple configurations (including empty ones) for a single package and removed some of them. In your case, if you had 16 forms of `(el-get-bundle iedit ...)` and you have removed the last one, then the behavior is expected. You see `_xxxx-16_iedit.el` but it is not loaded and you can safely remove it.

For now, `el-get-bundle` has no way to clean unused configuration caches in `el-get-bundle-init-directory`. If you want to keep it clean, you can just remove the whole `el-get-bundle-init-directory` and restarting Emacs will generate used ones. (Don't do this every time or your Emacs startup gets slower.)

If you are sure that the duplicated ones are both loaded, or they are generated after you removed `el-get-bundle-init-directory`, then it's a bug, so please let us know that.

**Comment by enzochiau** [comment]
Got it. Just as what you said, after clean directory, there's no duplicated ones.
