### ISSUE TITLE
ensime recipe file "mode specification error: (wrong-number-of-arguments.."

### ISSUE THREAD

**Issue by rexshihaoren** [dimitri/el-get#2442]
#### Example: How to reproduce error
1. init.el: https://gist.github.com/rexshihaoren/079fe1a592a8b2d4ba17293375def63a
2. git clone  https://github.com/rexshihaoren/progfun1.git
3. emacs progfun1/example
4. open any .scala file, give me "ensime file mode specification error: (wrong-number-of-arguments...."

<img width="1440" alt="screen shot 2016-09-05 at 4 07 12 pm" src="https://cloud.githubusercontent.com/assets/1203972/18241297/e8da18c8-7382-11e6-930d-a4248334990d.png">

I have tested it with (use-package ensime :pin melpa-stable) in the init.el(https://gist.github.com/rexshihaoren/a4e140e0e7bab27cad20105c243cc02a) without using el-get and it worked without error.
Is there anyway for me to force ensime to use melpa-stable?

**Comment by syohex** [comment]
This is ensime issue.

https://github.com/ensime/ensime-emacs/blob/d2fa558cb872f1fc691efbb87f3a262389f53820/ensime-mode.el#L147

is wrong. `major-mode` function does not take arguments. But problems still exist. 

https://github.com/dimitri/el-get/blob/f355aef81d620f2477875995340b209ff8c5e06d/recipes/ensime.rcp#L15

el-get recipe sets `ensime-scala-mode-hook` to `scala-mode-hook`, this causes infinite loop. because `ensime-scala-mode-hook` calls `scala-mode` in it. el-get recipe should not call `ensime-scala-mode-hook`.
