### ISSUE TITLE
could not download cedet

### ISSUE THREAD

**Issue by weeshy** [dimitri/el-get#2533]
I'm trying to `el-get-install cedet`. It instantly passed download phase without actually downloading anything. After that el-get failed at the build phase because _el-get/bin/cedet_ folder is empty. I tried to clone git url manually and got success.

**Comment by npostavs** [comment]
The el-get recipe just uses the CEDET that's builtin to Emacs for version 23.3 and higher, so there is nothing for it to do. It shouldn't do anything in the build phase either. Should be fixed by #2539. 

See also #2502 for discussion about whether the cedet should be using the builtin version or not...
