### ISSUE TITLE
Replace deprecated cl by cl-lib

### ISSUE THREAD

**Issue by stephan-cr** [dimitri/el-get#2792]
Since Emacs 27, the package cl is deprecated (and issues a warning: `Package cl is deprecated`). The replacement for cl is cl-lib.

I would like to provide a PR which ports all el-get code to use cl-lib, instead of cl. For this, it would be best to drop support for Emacs versions less than 24.3, because since Emacs 24.3, cl-lib is builtin and doesn't need an extra package from ELPA.

What do you think, can I go ahead?

**Comment by yyr** [comment]
I think its reasonable to drop support for <24.3. its almost 8 years passed since 24.2 is released. I still come across earlier versions of emacs on some linux servers that I use, but again with so many incompatibilities, now a days I tend to install latest version of emacs in home directory on those servers.

So yes, I support such a change.

**Comment by thoni56** [comment]
Emacs now issues a deprecation warning for `cl`, so it is time ;-)

I tried just simple-minded replace all `(require 'cl)` with `(require 'cl-lib)` which seems to be the prefered replacement, but the tests did not run with that change...

**Comment by stephan-cr** [comment]
PR has been merged, therefore, it can be closed.
